### ISSUE TITLE
Strikethrough and italic are missing

### ISSUE THREAD

**Issue by adriangalilea** [yym68686/md2tgmd#2]
Hello,

First of all thanks for sharing,

I've been struggling with an elegant solution to this,

All is working perfectly but strikethrough and italic don't seem to be working.

```
message_text = "Hello, **~~bold~~** text, *italic* text, ~~strikethrough~~ text."
styled_text = escape(message_text)
await bot.send_message(
            chat_id=user_id, parse_mode="MarkdownV2", text=styled_text
        )
```

<img width="420" alt="image" src="https://github.com/yym68686/md2tgmd/assets/90320947/0d7fb7ef-e1a8-4105-8708-49fa54544481">

**Comment by yym68686** [comment]
Thank you for your support. Strikethrough and italics are not currently supported, but they have been added to my development plan. If time permits, I will implement this feature as soon as possible

**Comment by jrojer** [comment]
@yym68686 if you briefly explain how to add it, I can add it

**Comment by yym68686** [comment]
Hello, italics and strikethrough are now supported.
