### ISSUE TITLE
emoji 无法被转换成 v2 格式

### ISSUE THREAD

**Issue by bitqiu** [yym68686/md2tgmd#6]

**Comment by yym68686** [comment]
什么样子的emoji？

**Comment by bitqiu** [comment]
会员 emoji

**Comment by bitqiu** [comment]
在 markdownv2 中应该是
` ![💰](tg://emoji?id=5458649471799795648)`

**Comment by yym68686** [comment]
这个emoji怎么在tg显示啊，我在tg里面打不开链接：tg://emoji?id=5458649471799795648

**Comment by bitqiu** [comment]
会员 emoji 
<img width="339" alt="image" src="https://github.com/yym68686/md2tgmd/assets/4955106/b80805d9-de9e-49bd-a98c-e25451d59925">

**Comment by yym68686** [comment]
这个没办法显示，因为 telegram 客户端传递给机器人会自动转换为标准的表情。比如“😊”，是没有动画效果的。而且我也没办法通过链接（tg://emoji?id=5458649471799795648）的方式显示表情。

**Comment by bitqiu** [comment]
https://core.telegram.org/bots/api#markdownv2-style 
看文档
会员的 emoji 会传 emoji id 过来的
<img width="636" alt="image" src="https://github.com/yym68686/md2tgmd/assets/4955106/10baaad1-6e8a-4048-8f53-2805dc120060">

**Comment by yym68686** [comment]
这个实现不了，telegram 客户端不支持用链接的方式显示会员表情。目前只能点按表情面板来发送会员表情。

机器人是能正常发送 markdown 格式的链接的，但是 telegram 客户端并不会把链接解析为会员表情。
